all:
	@echo "Targets: "
	@echo "  compile    Compile software packages"
	@echo "  clean      Remove intermediate files"

clean:
	cd hal;         make clean; cd ..
	cd mul64;       make clean; cd ..

compile:
	cd hal;         make compile; cd ..
	cd mul64;       make compile; cd ..
